{% set version = "1.1-12" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-survpresmooth
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/survPresmooth_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/survPresmooth/survPresmooth_{{ version }}.tar.gz
  sha256: 9370b21b370bb2308597ada70decceecd6b93ca0ea45e70259f977c7304dc589

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('survPresmooth')"           # [not win]
    - "\"%R%\" -e \"library('survPresmooth')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=survPresmooth
  license: GPL-2.0-only
  summary: Presmoothed estimators of survival, density, cumulative and non-cumulative hazard functions with right-censored survival data.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: survPresmooth
# Type: Package
# Title: Presmoothed Estimation in Survival Analysis
# Version: 1.1-10
# Date: 2017-09-06
# Author: Ignacio Lopez de Ullibarri <ilu@udc.es> [aut, cre], Maria Amalia Jacome <majacome@udc.es> [aut]
# Maintainer: Ignacio Lopez de Ullibarri <ilu@udc.es>
# Depends: R(>= 3.0.1)
# Description: Presmoothed estimators of survival, density, cumulative and non-cumulative hazard functions with right-censored survival data.
# License: GPL-2
# NeedsCompilation: yes
# LazyData: yes
# Packaged: 2017-09-06 09:44:02 UTC; ilu
# Repository: CRAN
# Date/Publication: 2017-09-06 10:39:20 UTC
